name: Daily API Call

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: current_date
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"
      - uses: actions/checkout@v2   
      - name: Run Script
        env: 
            REMINDER_API_KEY: ${{ secrets.REMINDER_API_KEY }}
            REMINDER_SERVICE: "https://birthday-calender.vercel.app"
        run: |
          . ./reminder.sh "${{steps.current_date.outputs.date}}" "$REMINDER_SERVICE" "$REMINDER_API_KEY"
