name: Daily API Call

on:
  schedule:
    - cron: '0 7 * * *'
  push:
    branches:
        - main

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: current_date
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"
      
      - name: Make API Call
        env: 
            REMINDER_API_KEY: ${{ secrets.REMINDER_API_KEY }}
            REMINDER_SERVICE: "https://birthday-calender.vercel.app"
        run: |
          curl "$REMINDER_SERVICE/api/events/reminder?date=${{steps.current_date.outputs.date}}" \
            -H "Api-Key: $REMINDER_API_KEY" \
            --compressed
